.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH GPGDIR 8 "February, 2003" Linux
.SH NAME
.B gpgdir
.SH SYNOPSIS
.B gpgdir [-e
.I directory
.B ] [-d
.I directory
.B ] [-g
.I directory
.B ] [-p
.I pw-file
.B ] [--Exclude
.I pattern
.B ] [--Exclude-from
.I file
.B ] [--no-recurse] [--no-delete] [--no-preserve-times] [-t] [-s] [-V] [-v] [-h]
.SH DESCRIPTION
.B gpgdir
is a perl script that uses the CPAN GnuPG perl module to encrypt and decrypt
directories using a gpg key specified in ~/.gpgdirrc.
.B gpgdir
recursively descends through a directory in order to make sure it encrypts or
decrypts every file in a directory and all of its subdirectories.  By default
the mtime and atime values of all files will be preserved upon encryption and
decryption (this can be disabled with the
.B --no-preserve-times
option).  Note that in
.B --encrypt
mode, gpgdir will delete the original files that
it successfully encrypts (unless the
.B --no-delete
option is given).  However,
upon startup gpgdir first asks for a the decryption password to be sure that a
dummy file can successfully be encrypted and decrypted.  The initial test can
be disabled with the
.B --skip-test
option so that a directory can easily be encrypted without having to also
specify a password (this is consistent with
.B gpg
behavior).  Also, note that gpgdir is careful not encrypt hidden files and
directories.  After all, you probably don't want your ~/.gnupg directory or
~/.bashrc file to be encrypted.

.SH OPTIONS
.PP
.PD 0
.TP

.BR \-e ", " \-\^\-encrypt\ \<directory>
Encrypt the directory specified on the command line.
.TP

.BR \-d ", " \-\^\-decrypt\ \<directory>
Decrypt the directory specified on the command line.
.TP

.BR \-g ", " \-\^\-gnupg-dir\ \<directory>
Specify which .gnupg directory will be used to find GPG keys.  The default
is ~/.gnupg if this option is not used.  This option allows gpgdir to be
run as one user but use the keys of another user (assuming permissions are
setup correctly, etc.).
.TP

.BR \-p ", " \-\^\-pw-file\ \<pw-file>
Read decryption password from
.B pw-file
instead of typing it on the command line.
.TP

.BR \-t ", " \-\^\-test-mode
Run an encryption and decryption test against a dummy file and exit.  This
test is always run by default in both
.B --encrypt
and
.B --decrypt
mode.
.TP

.BR \-\^\-Exclude\ \<pattern>
Instruct gpgdir to skip all files that match
.B pattern
as a regex match against each filename.  This is similar to the
.B --exclude
option in the standard GNU tar command.
.TP

.BR \-\^\-Exclude-from\ \<file>
Instruct gpgdir to exclude all files matched by patterns listed in
.B file.
This is similar to the
.B --exclude-from
the GNU tar command.
.TP

.BR " \-\^\-skip-test
Skip encryption and decryption test.  This will allow
.B gpgdir
to be used to encrypt a directory without specifying a password (which
normally gets used in encryption mode to test to make sure decryption
against a dummy file works properly).
.TP

.BR \-\^\-no-recurse
Instruct gpgdir to not recurse through any subdirectories of the directory
that is being encrypted or decrypted.
.TP

.BR \-\^\-no-delete
Instruct gpgdir to not delete original files at encrypt time.
.TP

.BR \-\^\-no-preserve times
Instruct gpgdir to not preserve original file mtime and atime values
upon encryption or decryption.
.TP

.BR \-v ", " \-\^\-verbose
Run in verbose mode.
.TP

.BR \-V ", " \-\^\-Version
Print version number and exit.
.TP

.BR \-h ", " \-\^\-help
Print usage information and exit.
.TP

.SH FILES
.B ~/.gpgdirrc
.RS
Contains the key id of the user gpg key that will be used to encrypt
or decrypt the files within a directory.
.RE

.SH EXAMPLES
The following examples illustrate the command line arguments that could
be supplied to gpgdir in a few situations:

To encrypt a directory:

.B $ gpgdir -e ~/testdir

To decrypt a directory:

.B $ gpgdir -d ~/testdir

To encrypt a directory but skip all filenames that contain the string "host":

.B $ gpgdir -e ~/testdir --Exclude host

To encrypt a directory but skip the encryption/decryption test (so you will
not be prompted for a decryption password):

.B $ gpgdir -e ~/testdir -s

To encrypt a directory and no subdirectories:

.B $ gpgdir -e /home/user/testdir --no-recurse

To encrypt root's home directory, but use the GPG keys associated with the user "bob":

.B # gpgdir -e /root -g /home/bob/.gnupg

.SH DEPENDENCIES
.B gpgdir
requires that gpg, the Gnu Privacy Guard (http://www.gnupg.org) is installed.
.B gpgdir
also requires the GnuPG perl module from CPAN, but it is bundled with
.B gpgdir
and is installed in /usr/lib/gpgdir at install-time so it does not pollute the
system perl library tree.

.SH "SEE ALSO"
.BR gpg (1)

.SH AUTHOR
Michael Rash <mbr@cipherdyne.org>

.SH BUGS
Send bug reports to mbr@cipherdyne.org. Suggestions and/or comments are
always welcome as well.

.SH DISTRIBUTION
.B gpgdir
is distributed under the GNU General Public License (GPL), and the latest
version may be downloaded from
.B http://www.cipherdyne.org
